### ISSUE TITLE
Changing the output from cairo.dll to libcairo-2.dll?

### ISSUE THREAD

**Issue by tonyvsuk** [preshing/cairo-windows#14]
Hello,

First of all thanks so much for this. I've followed the instructions and built the DLLs without any problems at all, used it in my app and it's really improved the graphics performance (it's a wxWidgets based application). Rendering on Windows was slow, now it's much faster.

wxWidgets is hard coded to try and load "libcairo-2.dll". I can change that easily with a patch on my build system. It seems though that the pre-built binaries mentioned on the cairo download page is named "libcairo-2.dll".

So would it be best to also output libcairo-2.dll from this script as well?

I'm only asking as I need to either modify wxWidgets to use cairo.dll and link with cairo.lib, or change your script to output libcairo-2.dll and libcairo-2.lib (I cannot just rename the lib as it will still expect to find cairo.dll).

Thanks again,

Tony.

**Comment by preshing** [comment]
Hey Tony, glad the script worked for you. If you want, you can try pre-downloading the cairo source code and see if you can change the output filenames to libcairo-2.* in Makefile.win32 (I think it's defined there somewhere). Then just run this script against that source code instead. That ought to produce the files you need.

But I don't think I will change the output name in this repo because it involves work 😄 and I have my own apps that depend on the cairo.lib/dll names. Also It's the name used in the original cairo Makefile, but like I said you can always change it for your needs.
