### ISSUE TITLE
Error C2220: No Executable File Generated

### ISSUE THREAD

**Issue by trainingmode** [preshing/cairo-windows#2]
Hello! I've been attempting to build this for the past day, but ended up on a strange linking error that I couldn't overcome. The script finishes all the way past the cairo code files, but generates errors from "zlib/deflate.c" once it tries to make the final lib for cairo. [Here's a screenshot of the x86 Command Prompt](https://i.imgur.com/AIXaeDs.png).

**Comment by kevinlearnprogramming** [comment]
Hello @preshing,
I used VS 2019 and generated 4 dependencies successfully but  when build cairo I encountered the same @trainingmode's issue, I tried to fix "error C2220: warning treated as error" but It doesn't work. Could you help me check. 

Thanks in advance.
<a href="https://github.com/preshing/cairo-windows/files/3826878/build_fail_cairo_lib.txt">Refer build log</a>

**Comment by preshing** [comment]
Hello,

This issue was caused by Spectre mitigation warnings added to the latest Visual Studio 2017 & 2019 updates.

I fixed it by disabling warning C5045 in the script as seen [here](https://github.com/preshing/cairo-windows/blob/76335f8cabd064247efb0855b5af965456c624b1/build-cairo-windows.sh#L65).

Hope it will work for you now.
